### ISSUE TITLE
Allow lower bid amounts.

### ISSUE THREAD

**Issue by braedenlane** [TreyDettmer/Pinochle#2]
The game forces the starting bid to be around 250, but because of that, it makes it difficult to want to bid and take control of the trump suit.

Severity: Improvement Suggestion
Component: Game Rules

In playing the game, especially when in the lead by a lot, a bid of 250 can be intimidating, especially because if you lose, you can end up going negative. Being able to start the bid at a lower value might make the game a bit better. Even being able to enter a bid manually rather than having two options to choose from.

To recreate:
Start game.
See bid offered.
Notice how it is high.

**Comment by alexjmak** [comment]
Nice suggestion, however, Pinochle rules generally do not allow bidding below 250. I do understand it maybe difficult though.

**Comment by braedenlane** [comment]
Gotcha, thanks for clarifying! Since this was just an improvement suggestion, that's fine!
