### ISSUE TITLE
Difficult to determine who played what card.

### ISSUE THREAD

**Issue by MwKau** [TreyDettmer/Pinochle#3]
It is hard to track who played which card, for example if your teammate skips.

Severity: Suggestion/Improvement
Component: GUI

It its not possible to communicate with your AI teammate, so It could be beneficial to include whether a card was played by your teammate or not. The current way to do this is keep track of who has waiting and who is not. To improve this, you might want to add a card moving animation to show where each card is from. You could also add more of a delay between AI playing cards.

To recreate this, the user should start a game with 3 computer players and 1 human player. Notice that cards appear without indication of source and in rapid succession.

**Comment by alexjmak** [comment]
Fixed. Cards are placed in front of the player, winner is highlighted.

**Comment by RJMNillo** [comment]
Was not an issue I wrote about, but can confirm this works.

**Comment by MwKau** [comment]
This is very cool! Good work
