### ISSUE TITLE
Not sure about Pinochle-Design Document, but limited strictly to 4 players.

### ISSUE THREAD

**Issue by VandanBh** [TreyDettmer/Pinochle#4]
Description: In the main menu, you are not allowed to add or remove a player, but, in some other Pinochle games I found while trying to look up directions on how to play the game, they allowed a 3-player game. I'm not sure if you intended that or not in your design document. If you didn't, and you only want to keep it four players, a light suggestion would be to remove the "X" icon and the AddPlayer Button in the main menu.

Severity: Very Minor / Suggestion / Improvement
Component: Game Rules / Main Menu

Reproduce: Open the game, and try pressing the X icon to delete a player or the add Player button to add a player, and it just responds with the specifications.

**Comment by alexjmak** [comment]
Nice suggestion! We are sticking with four players per the requirements document, however.
