### ISSUE TITLE
Allow a Toggle for negative scoring

### ISSUE THREAD

**Issue by RJMNillo** [TreyDettmer/Pinochle#5]
Component: Game Rules
Severity: Improvement suggestion

The scores do get subtracted if a team does not meet the bid, the score gets subtracted from their total. Beginner teams may tend to go way below, reaching the negative scores, leaving them far behind.

To Reproduce:
- Start game
- Make some bad moves to not meet the requirement
- see that the score reaches negative

**Comment by alexjmak** [comment]
Nice suggestion! Did not get enough time to implement however and Pinochle generally does not allow this.

**Comment by RJMNillo** [comment]
Improvement not implemented, but the explanation as a general rule is understandable and based on some tradtion.

No points marked off
