### ISSUE TITLE
Trump suit not working.

### ISSUE THREAD

**Issue by Gmunster33** [TreyDettmer/Pinochle#6]
This is a minor game rules bug. The trump cards do not win tricks of another starting suit when validly played.

The bug occurs when another player starts a trick with a non-trump suit, and you do not have a card of that suit. However, you do have trump cards remaining. When you play a trump card under these circumstances, it should automatically win the trick unless another player produces a higher magnitude trump card. You do not win the trick.

**Comment by alexjmak** [comment]
Fixed

**Comment by lpszeto** [comment]
The trump card is now fixed which is excellent.

**Comment by Gmunster33** [comment]
When another player starts a trick with a non-trump suit, and you do not have a card of that suit, trump cards of any denomination take the trick. Well done!
